version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gosat-app
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    volumes:
      - ./dist:/usr/share/nginx/html
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
